# Generated by Django 4.1.3 on 2022-11-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_text_tag_name_alter_scope_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='teg',
            new_name='tags',
        ),
    ]
